"use client";

import { useMemo, useState } from "react";
import { Loader2, Search, ShieldCheck } from "lucide-react";

type User = { id: string; name: string | null; email: string; role: string; createdAt: string };
const roles = ["CUSTOMER", "VENDOR", "RECRUITER", "ADMIN"];

export function AdminUsersTable({ users: initialUsers, currentAdminId }: { users: User[]; currentAdminId: string }) {
  const [users, setUsers] = useState(initialUsers); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ALL"); const [updating, setUpdating] = useState<string | null>(null);
  const visibleUsers = useMemo(() => users.filter((user) => (filter === "ALL" || user.role === filter) && `${user.name || ""} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [filter, query, users]);
  async function updateRole(userId: string, role: string) { setUpdating(userId); const response = await fetch("/api/admin/users", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, role }) }); if (response.ok) setUsers((current) => current.map((user) => user.id === userId ? { ...user, role } : user)); setUpdating(null); }
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-4">{roles.map((role) => <div key={role} className="rounded-xl border bg-white p-4 dark:bg-gray-900"><p className="text-xs font-bold uppercase tracking-wide text-gray-500">{role.toLowerCase()}s</p><p className="mt-1 text-2xl font-black">{users.filter((user) => user.role === role).length}</p></div>)}</div><div className="flex flex-col gap-3 rounded-2xl border bg-white p-4 dark:bg-gray-900 sm:flex-row sm:justify-between"><label className="relative block sm:w-80"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or email" className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm dark:bg-gray-800" /></label><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-lg border px-3 py-2 text-sm dark:bg-gray-800"><option value="ALL">All roles</option>{roles.map((role) => <option key={role}>{role}</option>)}</select></div><div className="overflow-x-auto rounded-2xl border bg-white dark:bg-gray-900"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-gray-500"><th className="p-4">Account</th><th>Joined</th><th className="pr-4">Role</th></tr></thead><tbody>{visibleUsers.map((user) => <tr key={user.id} className="border-b last:border-0"><td className="p-4"><p className="font-semibold">{user.name || "Unnamed user"}{user.id === currentAdminId && <span className="ml-2 text-xs text-blue-600">You</span>}</p><p className="mt-1 text-xs text-gray-500">{user.email}</p></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td className="pr-4"><select aria-label={`Set role for ${user.email}`} value={user.role} disabled={user.id === currentAdminId || updating === user.id} onChange={(event) => updateRole(user.id, event.target.value)} className="rounded-lg border px-2 py-1.5 text-xs font-bold dark:bg-gray-800">{roles.map((role) => <option key={role}>{role}</option>)}</select>{updating === user.id ? <Loader2 className="ml-2 inline h-3.5 w-3.5 animate-spin text-blue-600" /> : user.role === "ADMIN" && <ShieldCheck className="ml-2 inline h-3.5 w-3.5 text-blue-600" />}</td></tr>)}</tbody></table>{!visibleUsers.length && <p className="p-8 text-center text-sm text-gray-500">No accounts match this filter.</p>}</div></div>;
}
