import { LifeBuoy } from "lucide-react";
import Link from "next/link";
import { requireAdmin } from "@/lib/rbac";
import { prisma } from "@/lib/prisma";
import { DisputeActions } from "./DisputeActions";

const statuses = ["OPEN", "UNDER_REVIEW", "RESOLVED", "REJECTED"] as const;
const filters = ["ALL", ...statuses] as const;

export default async function AdminDisputesPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const selectedStatus = filters.includes(query.status as (typeof filters)[number]) ? query.status as (typeof filters)[number] : "OPEN";
  const disputes = await prisma.dispute.findMany({ where: selectedStatus === "ALL" ? undefined : { status: selectedStatus }, include: { user: { select: { name: true, email: true } }, order: { select: { orderNumber: true, totalAmount: true, status: true, payment: { select: { provider: true, reference: true, status: true } } } } }, orderBy: { createdAt: "desc" } });

  return <section className="space-y-6"><div><h1 className="flex items-center gap-2 text-2xl font-black"><LifeBuoy className="h-6 w-6 text-blue-600" /> Order support requests</h1><p className="mt-1 text-sm text-gray-500">Review buyer issues. Recording a resolution here does not automatically issue a payment refund.</p></div><nav aria-label="Support case status" className="flex flex-wrap gap-2">{filters.map((status) => <Link key={status} href={`/dashboard/admin/disputes?status=${status}`} className={`rounded-full px-3 py-1.5 text-xs font-bold transition ${selectedStatus === status ? "bg-blue-600 text-white" : "border bg-white text-gray-600 hover:border-blue-300 hover:text-blue-700 dark:bg-gray-900 dark:text-gray-300"}`}>{status.replace("_", " ")}</Link>)}</nav><div className="overflow-x-auto rounded-2xl border bg-white dark:bg-gray-900"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-gray-500"><th className="p-4">Order & buyer</th><th>Issue & timeline</th><th>Payment</th><th className="pr-4">Resolution</th></tr></thead><tbody>{disputes.map((dispute) => <tr key={dispute.id} className="border-b align-top last:border-0"><td className="p-4"><p className="font-bold">#{dispute.order.orderNumber}</p><p className="mt-1 text-xs text-gray-500">{dispute.user.name || dispute.user.email}</p><p className="mt-1 text-xs font-semibold text-blue-600">₦{dispute.order.totalAmount.toLocaleString()}</p></td><td className="max-w-sm py-4 pr-4"><p className="text-xs font-bold text-gray-500">{dispute.reason.replaceAll("_", " ")}</p><p className="mt-1 whitespace-pre-wrap text-sm">{dispute.details}</p><p className="mt-2 text-[11px] text-gray-500">Submitted {new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(dispute.createdAt)}</p><p className="text-[11px] text-gray-500">Last updated {new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(dispute.updatedAt)}</p></td><td className="py-4 pr-4 text-xs"><p className="font-bold">{dispute.order.payment?.status || "No payment"}</p><p className="mt-1 text-gray-500">{dispute.order.payment?.provider}</p><p className="mt-1 break-all text-[10px] text-gray-500">{dispute.order.payment?.reference}</p></td><td className="py-4 pr-4"><DisputeActions id={dispute.id} initialStatus={dispute.status} initialNote={dispute.adminNote} /></td></tr>)}</tbody></table>{!disputes.length && <p className="p-8 text-center text-sm text-gray-500">No {selectedStatus === "ALL" ? "" : `${selectedStatus.toLowerCase().replace("_", " ")} `}support requests.</p>}</div></section>;
}
